version: "3.8"
services:
  db:
    image: postgres:15
    container_name: local_pgdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
     - local_pgdata:/var/lib/postgresql/18/docker
     - ./db/init.sql:/docker-entrypoint-initdb.d/initdb.sql
volumes:
  local_pgdata: