## PostgreSQL
spring.datasource.username=test
spring.datasource.password=test
spring.flyway.locations = classpath:db.migration/general, classpath:db.migration/integration

spring.security.oauth2.client.registration.google.client-id=439117022433-ic37qhs7ba358l4fv8956spqm4o2f8h4.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=sdfsdff34f34f34ffsdfs